# Generated by Django 5.0.1 on 2024-02-16 04:38

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.good_directory_path),
        ),
    ]
